@section('title', 'BAC - Abstract of Quotations')

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-2xl text-gray-800 leading-tight">
            {{ __('Abstract of Quotations: ') . $purchaseRequest->pr_number }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            
            @if(session('status'))
                <div class="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg">
                    {{ session('status') }}
                </div>
            @endif

            @if(session('error'))
                <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
                    {{ session('error') }}
                </div>
            @endif

            {{-- AOQ Status Card --}}
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-semibold mb-4">AOQ Status</h3>
                    
                    @if($validation['can_generate'])
                        <div class="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg mb-4">
                            <div class="flex items-center">
                                <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                                </svg>
                                <span class="font-semibold">Ready to Generate AOQ</span>
                            </div>
                            <p class="mt-2 text-sm">All items have been evaluated and all ties have been resolved.</p>
                        </div>
                        
                        <form action="{{ route('bac.quotations.aoq.generate', $purchaseRequest) }}" method="POST" onsubmit="return confirm('Are you sure you want to generate the Abstract of Quotations?');">
                            @csrf
                            <button type="submit" class="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors">
                                <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                                </svg>
                                Generate AOQ Document
                            </button>
                        </form>
                    @else
                        <div class="bg-yellow-50 border border-yellow-200 text-yellow-800 px-4 py-3 rounded-lg">
                            <div class="flex items-center mb-2">
                                <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                                </svg>
                                <span class="font-semibold">Cannot Generate AOQ Yet</span>
                            </div>
                            <ul class="list-disc list-inside text-sm space-y-1">
                                @foreach($validation['errors'] as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>

            {{-- Previously Generated AOQs --}}
            @if($aoqGenerations->isNotEmpty())
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6">
                        <h3 class="text-lg font-semibold mb-4">Previously Generated AOQs</h3>
                        <div class="overflow-x-auto">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reference Number</th>
                                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Items/Suppliers</th>
                                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach($aoqGenerations as $generation)
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap font-semibold text-blue-600">{{ $generation->aoq_reference_number }}</td>
                                            <td class="px-6 py-4 whitespace-nowrap">{{ $generation->generatedBy->name }}</td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ $generation->created_at->format('M d, Y h:i A') }}</td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ $generation->total_items }} items / {{ $generation->total_suppliers }} suppliers</td>
                                            <td class="px-6 py-4 whitespace-nowrap">
                                                <a href="{{ route('bac.quotations.aoq.download', [$purchaseRequest, $generation->id]) }}" class="text-blue-600 hover:text-blue-900">
                                                    Download
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @endif

            {{-- AOQ Data Table --}}
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-semibold mb-4">Quotation Evaluation</h3>
                    
                    <div class="overflow-x-auto">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Item</th>
                                    <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Qty</th>
                                    @foreach($quotations as $quotation)
                                        <th class="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase">
                                            {{ $quotation->supplier->business_name }}
                                        </th>
                                    @endforeach
                                    <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Decision</th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200">
                                @foreach($aoqData as $itemData)
                                    @php
                                        $item = $itemData['item'];
                                        $hasTie = $itemData['has_tie'];
                                        $winners = $itemData['winners'];
                                    @endphp
                                    <tr>
                                        <td class="px-4 py-4">
                                            <div class="text-sm font-medium text-gray-900">{{ $item->item_name }}</div>
                                            <div class="text-xs text-gray-500">{{ $item->unit_of_measure }}</div>
                                        </td>
                                        <td class="px-4 py-4 text-sm text-gray-900">{{ $item->quantity_requested }}</td>
                                        
                                        @foreach($quotations as $quotation)
                                            @php
                                                $quoteItem = collect($itemData['quotes'])->firstWhere('quotation.id', $quotation->id);
                                            @endphp
                                            <td class="px-4 py-4 text-center">
                                                @if($quoteItem)
                                                    @php
                                                        $qi = $quoteItem['quotation_item'];
                                                        $bgColor = '';
                                                        $badgeColor = 'bg-gray-500';
                                                        
                                                        if ($qi->isDisqualified()) {
                                                            $bgColor = 'bg-red-100';
                                                            $badgeColor = 'bg-red-600';
                                                        } elseif ($qi->is_winner) {
                                                            $bgColor = 'bg-green-100';
                                                            $badgeColor = 'bg-green-600';
                                                        } elseif ($qi->is_tied) {
                                                            $bgColor = 'bg-yellow-100';
                                                            $badgeColor = 'bg-yellow-600';
                                                        } elseif ($qi->is_lowest) {
                                                            $bgColor = 'bg-blue-50';
                                                            $badgeColor = 'bg-blue-600';
                                                        }
                                                    @endphp
                                                    <div class="{{$bgColor}} p-2 rounded">
                                                        <div class="text-sm font-semibold">₱ {{ number_format($qi->total_price, 2) }}</div>
                                                        <div class="text-xs text-gray-600">₱ {{ number_format($qi->unit_price, 2) }} each</div>
                                                        <div class="text-xs mt-1">
                                                            <span class="px-2 py-1 rounded text-white text-xs {{$badgeColor}}">
                                                                {{ $qi->getAoqStatusLabel() }}
                                                            </span>
                                                        </div>
                                                        @if($qi->isDisqualified())
                                                            <div class="text-xs text-red-700 mt-1 font-semibold">{{ $qi->disqualification_reason }}</div>
                                                        @elseif($qi->rank)
                                                            <div class="text-xs text-gray-500 mt-1">Rank: {{ $qi->rank }}</div>
                                                        @endif
                                                    </div>
                                                @else
                                                    <span class="text-gray-400 text-sm">No quote</span>
                                                @endif
                                            </td>
                                        @endforeach
                                        
                                        <td class="px-4 py-4">
                                            @if($hasTie)
                                                <button 
                                                    onclick="openTieResolutionModal({{ $item->id }}, '{{ $item->item_name }}', {{ json_encode($itemData['quotes']) }})"
                                                    class="px-3 py-1 bg-yellow-600 text-white text-xs rounded hover:bg-yellow-700">
                                                    Resolve Tie
                                                </button>
                                            @elseif(count($winners) > 0)
                                                @php
                                                    $winner = reset($winners);
                                                    $winnerSupplier = $winner['quotation']->supplier->business_name;
                                                @endphp
                                                <div class="text-sm">
                                                    <span class="font-semibold text-green-600">{{ $winnerSupplier }}</span>
                                                    <button 
                                                        onclick="openBacOverrideModal({{ $item->id }}, '{{ $item->item_name }}', {{ json_encode($itemData['quotes']) }})"
                                                        class="ml-2 px-2 py-1 bg-orange-600 text-white text-xs rounded hover:bg-orange-700">
                                                        Override
                                                    </button>
                                                </div>
                                            @else
                                                <span class="text-gray-400 text-sm">No winner</span>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="flex justify-between">
                <a href="{{ route('bac.quotations.manage', $purchaseRequest) }}" class="inline-flex items-center px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700">
                    Back to Quotations
                </a>
            </div>
        </div>
    </div>

    {{-- Tie Resolution Modal --}}
    <div id="tieResolutionModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
        <div class="relative top-20 mx-auto p-5 border w-11/12 md:w-3/4 lg:w-1/2 shadow-lg rounded-md bg-white">
            <div class="mt-3">
                <h3 class="text-lg font-semibold text-gray-900 mb-4">Resolve Tie</h3>
                <form id="tieResolutionForm" method="POST" action="{{ route('bac.quotations.aoq.resolve-tie', $purchaseRequest) }}">
                    @csrf
                    <input type="hidden" name="purchase_request_item_id" id="tie_item_id">
                    
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Item:</label>
                        <p id="tie_item_name" class="text-gray-900"></p>
                    </div>
                    
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Select Winner:</label>
                        <select name="winning_quotation_item_id" id="tie_winner_select" required class="w-full border-gray-300 rounded-md shadow-sm">
                            <option value="">-- Select Supplier --</option>
                        </select>
                    </div>
                    
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Justification: <span class="text-red-500">*</span></label>
                        <textarea name="justification" required minlength="10" maxlength="1000" rows="4" 
                            class="w-full border-gray-300 rounded-md shadow-sm" 
                            placeholder="Explain why this supplier was selected..."></textarea>
                        <p class="text-xs text-gray-500 mt-1">Minimum 10 characters required</p>
                    </div>
                    
                    <div class="flex justify-end space-x-3">
                        <button type="button" onclick="closeTieResolutionModal()" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">
                            Cancel
                        </button>
                        <button type="submit" class="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700">
                            Save Decision
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- BAC Override Modal --}}
    <div id="bacOverrideModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
        <div class="relative top-20 mx-auto p-5 border w-11/12 md:w-3/4 lg:w-1/2 shadow-lg rounded-md bg-white">
            <div class="mt-3">
                <h3 class="text-lg font-semibold text-gray-900 mb-4">BAC Override</h3>
                <div class="bg-orange-50 border border-orange-200 text-orange-800 px-4 py-3 rounded-lg mb-4">
                    <p class="text-sm font-semibold">Warning: This will override the automatically determined winner.</p>
                    <p class="text-xs mt-1">Provide a detailed justification for audit purposes.</p>
                </div>
                <form id="bacOverrideForm" method="POST" action="{{ route('bac.quotations.aoq.bac-override', $purchaseRequest) }}">
                    @csrf
                    <input type="hidden" name="purchase_request_item_id" id="override_item_id">
                    
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Item:</label>
                        <p id="override_item_name" class="text-gray-900"></p>
                    </div>
                    
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Select New Winner:</label>
                        <select name="winning_quotation_item_id" id="override_winner_select" required class="w-full border-gray-300 rounded-md shadow-sm">
                            <option value="">-- Select Supplier --</option>
                        </select>
                    </div>
                    
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Justification: <span class="text-red-500">*</span></label>
                        <textarea name="justification" required minlength="20" maxlength="1000" rows="4" 
                            class="w-full border-gray-300 rounded-md shadow-sm" 
                            placeholder="Provide detailed justification for this override decision..."></textarea>
                        <p class="text-xs text-gray-500 mt-1">Minimum 20 characters required for override justification</p>
                    </div>
                    
                    <div class="flex justify-end space-x-3">
                        <button type="button" onclick="closeBacOverrideModal()" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400">
                            Cancel
                        </button>
                        <button type="submit" class="px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700">
                            Apply Override
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        function openTieResolutionModal(itemId, itemName, quotes) {
            document.getElementById('tie_item_id').value = itemId;
            document.getElementById('tie_item_name').textContent = itemName;
            
            const select = document.getElementById('tie_winner_select');
            select.innerHTML = '<option value="">-- Select Supplier --</option>';
            
            quotes.forEach(quote => {
                // Only show tied/lowest quotes that are NOT disqualified
                const isDisqualified = quote.quotation_item.disqualification_reason && quote.quotation_item.disqualification_reason.length > 0;
                
                if ((quote.quotation_item.is_tied || quote.quotation_item.is_lowest) && !isDisqualified) {
                    const option = document.createElement('option');
                    option.value = quote.quotation_item.id;
                    option.textContent = `${quote.quotation.supplier.business_name} - ₱${parseFloat(quote.total_price).toLocaleString('en-US', {minimumFractionDigits: 2})}`;
                    select.appendChild(option);
                }
            });
            
            document.getElementById('tieResolutionModal').classList.remove('hidden');
        }
        
        function closeTieResolutionModal() {
            document.getElementById('tieResolutionModal').classList.add('hidden');
            document.getElementById('tieResolutionForm').reset();
        }
        
        function openBacOverrideModal(itemId, itemName, quotes) {
            document.getElementById('override_item_id').value = itemId;
            document.getElementById('override_item_name').textContent = itemName;
            
            const select = document.getElementById('override_winner_select');
            select.innerHTML = '<option value="">-- Select Supplier --</option>';
            
            quotes.forEach(quote => {
                // Only show non-disqualified quotes
                const isDisqualified = quote.quotation_item.disqualification_reason && quote.quotation_item.disqualification_reason.length > 0;
                
                if (!isDisqualified) {
                    const option = document.createElement('option');
                    option.value = quote.quotation_item.id;
                    const isWinner = quote.quotation_item.is_winner ? ' (Current Winner)' : '';
                    option.textContent = `${quote.quotation.supplier.business_name} - ₱${parseFloat(quote.total_price).toLocaleString('en-US', {minimumFractionDigits: 2})}${isWinner}`;
                    select.appendChild(option);
                }
            });
            
            document.getElementById('bacOverrideModal').classList.remove('hidden');
        }
        
        function closeBacOverrideModal() {
            document.getElementById('bacOverrideModal').classList.add('hidden');
            document.getElementById('bacOverrideForm').reset();
        }
        
        // Close modals when clicking outside
        window.onclick = function(event) {
            const tieModal = document.getElementById('tieResolutionModal');
            const overrideModal = document.getElementById('bacOverrideModal');
            if (event.target === tieModal) {
                closeTieResolutionModal();
            }
            if (event.target === overrideModal) {
                closeBacOverrideModal();
            }
        }
    </script>
</x-app-layout>

